### ISSUE TITLE
Window shadow looses alpha-gradient

### ISSUE THREAD

**Issue by miwalter** [hermes83/compiz-windows-effect#1]
![shadow with gradient](https://user-images.githubusercontent.com/9148684/85852272-89aa7c00-b7b0-11ea-842b-68686b704c21.png)
![shadow without gradient](https://user-images.githubusercontent.com/9148684/85852274-8a431280-b7b0-11ea-869d-f60231fe258e.png)

Please have a look at the screenshots (top: normal window shadow, bottom: lost alpha gradient shadow) - whenever the extension is activated **and** the window gets moved, the shadow looses its alpha-gradient (but not its transparency at all).

The alpha-gradient comes back when the wobbly animation stops. Around two seconds after stopping to move the window (or releasing the mouse button) I would guess.

It's not a serious bug, it's a minor "glitch".

Maybe "lost" is to hard, the gradient seems to stop to early as if there is an invisible border around the window, so to speak.

Examples for applications/windows where it happens: chrome, libreoffice

It does NOT happen for nautilus, terminal etc... 

Maybe this is a not-gtk-issue? Don't know, just a wild guess.

**Comment by BlueManCZ** [comment]
I can confirm this. It happens with [compiz-alike-windows-effect](https://github.com/hermes83/compiz-alike-windows-effect) as well.

**Comment by hermes83** [comment]
The problem does not occur with new versions of gnome. It is therefore to be considered a problem of the platform rather than of the extension itself
