### ISSUE TITLE
The new default values are too exagerated

### ISSUE THREAD

**Issue by bugnano** [hermes83/compiz-windows-effect#11]
After the latest update of this extension, the windows wobble way too much.
I know that the parameters are tweakable, but I believe that the extension should have sensible defaults.

**Comment by MarcosWolf** [comment]
The same problem, try this fix

> please, try the following settings
> 
> ![immagine](https://user-images.githubusercontent.com/7895800/164502136-40786901-fe3f-4d79-951f-88c48fde55cb.png)
