### ISSUE TITLE
Wobbly windows are too exaggerated and settings don't seem to help/reduce it

### ISSUE THREAD

**Issue by kcken** [hermes83/compiz-windows-effect#12]
The new version causes the windows to wobble too much, and continue to wobble for too long.  I've tried adjusting the settings and set everything to zero (moved all bars all the way to the left), and they don't appear to have any impact - the wobbling is still too excessive
[Screencast from 04-21-2022 11:49:27 AM.zip](https://github.com/hermes83/compiz-windows-effect/files/8532525/Screencast.from.04-21-2022.11.49.27.AM.zip)
.

**Comment by hermes83** [comment]
please, try the following settings

![immagine](https://user-images.githubusercontent.com/7895800/164502136-40786901-fe3f-4d79-951f-88c48fde55cb.png)

**Comment by kcken** [comment]
Thanks - wasn't intuitive that moving the sliders to the right would reduce the effect; presumed moving right would enhance the effect.

**Comment by hermes83** [comment]
I understand, I tried to use the same behavior of the original effect in compiz for the parameters.
I hope that the extension is to your liking anyway

bye
