### ISSUE TITLE
Bad performance with tiled windows

### ISSUE THREAD

**Issue by Freeplayg** [hermes83/compiz-windows-effect#13]
On Fedora 36

https://user-images.githubusercontent.com/40742947/165181638-620abd9d-988c-427b-b656-1a17e1405ff5.mp4

**Comment by hermes83** [comment]
fixed with commit f1cdc5fb87b35471cdfc71c250bbcc19878caf7d

**Comment by hermes83** [comment]
fixed on Wayland with commit 8499a43aefc0e5cd8d43ca26d0e8eec420bf65ea
