### ISSUE TITLE
Wobbly windows for cinnamon [Feature request]

### ISSUE THREAD

**Issue by FallCheetah7373** [hermes83/compiz-windows-effect#14]
If it is *viable* to support linux mint cinnamon then please consider it as the current wobbly windows extension available on linuxmint/cinnamon-spices-extensions is broken.

**Comment by hermes83** [comment]
Hi, no extensions seems to work in Cinnamon 5.2.7. Are you sure Cinnamon still support extensions?

![immagine](https://user-images.githubusercontent.com/7895800/166073792-de416f85-0fc6-4b4a-bbc7-ab70ff7e5526.png)

**Comment by FallCheetah7373** [comment]
I would say 80% of extensions work you have to enable them using the plus icon

**Comment by hermes83** [comment]
thanks, it's not as intuitive as it might seem. It seems that everything needs to be rewritten, however I can try

**Comment by hermes83** [comment]
dear @FallCheetah7373 please check this new extension: [compiz windows effect cinnamon](https://github.com/hermes83/compiz-windows-effect-cinnamon)
