### ISSUE TITLE
Please , make it work with blur ( by blur my shell - extension )

### ISSUE THREAD

**Issue by tamaki03** [hermes83/compiz-windows-effect#15]
> Ubuntu 22.04 
> Gnome 42 - Wayland

This happens when i use compiz and blur my shell together

https://user-images.githubusercontent.com/90030004/170734353-b0257160-7110-4acb-adc5-34898c7ade48.mp4

I also created the same problem in github Blurmyshell
> https://github.com/aunetx/blur-my-shell/issues/264

It would be great if they could work together

**Comment by hermes83** [comment]
Can't reproduce, I can use both on:

> Arch Linux
> Gnome 42.1 - Wayland



https://user-images.githubusercontent.com/7895800/170762779-e0c29152-eabf-4c07-9018-7fd2d8e7e870.mp4

**Comment by 3pical** [comment]
I'm pretty sure you haven't enabled blur on the terminal or the compression makes it hard to see

**Comment by hermes83** [comment]
I see.
It would seem a problem related to the "blur my shell" extension.
The feature you are using is still in beta and they themselves indicate that it is a "buggy" feature.

![immagine](https://user-images.githubusercontent.com/7895800/170770244-d325b577-95f8-49ae-9063-d3ddd5e32c02.png)


I'm sorry but I doubt going to do anything with my extension.

**Comment by 3pical** [comment]
[> Unfortunately that is way harder to support than what I can do, and to expect something that work reliably (or that works at all to be honest), this bug need to be addressed to the Compiz extension maintainers instead -- but that will require them to implement a custom blur effect on top of their effect, etc...
](https://github.com/aunetx/blur-my-shell/issues/264#issuecomment-1139516811)
bruh

**Comment by hermes83** [comment]
the purpose of this extension is not to have a "blur" effect, nothing will be developed outside the scope of the extension (aka single responsibility principle). 
Special cases introduced by other extensions will not be handled in this extension and must be handled by those who introduced them
