### ISSUE TITLE
Magic Lamp effect

### ISSUE THREAD

**Issue by lugatto91** [hermes83/compiz-windows-effect#2]
Really great job. thank you so much for this awesome effect. Is it possible to recreate the magic lamp effect too?

**Comment by TheWeirdDev** [comment]
That would be awesome.

**Comment by hermes83** [comment]
Dear @lugatto91 
the magic lamp effect is work in progress: https://youtu.be/DtTO8B9VN-k
It will be a new extension

**Comment by hermes83** [comment]
The new magic lamp effect can be downloaded here:
https://extensions.gnome.org/extension/3740/compiz-alike-magic-lamp-effect

Note that if you use this extension it need to be updated
