### ISSUE TITLE
Support for Gnome 3.38

### ISSUE THREAD

**Issue by much-doge** [hermes83/compiz-windows-effect#3]
It would be great if this extension works on gnome 3.38

**Comment by hermes83** [comment]
Dear @much-doge, I'm waiting for extension review in gnome extensions portal.
You can see the review status here: https://extensions.gnome.org/review/

**Comment by much-doge** [comment]
Ahh I see, glad to know that because (it's trivial but) I like the extension, and many peoples too :D

**Comment by hermes83** [comment]
It's ready on gnome extension portal
