### ISSUE TITLE
Breaks on fractional scaling

### ISSUE THREAD

**Issue by fabiscafe** [hermes83/compiz-windows-effect#5]
If you move the window while you have fractional scaling enabled the window will jump to (i guess) 200% scaling until the animation is over and it will jump back to the original scaling.

See:
https://user-images.githubusercontent.com/18744080/124362980-cf5a1a00-dc38-11eb-8b5b-fb57e0c7cbdd.mp4

GNOME 40.1 (unpatched)
Archlinux
compiz-windows-effect from extensions.gnome.org

**Comment by MaKraMc** [comment]
I have the same Problem with 125% Scaling. :(

**Comment by stuaxo** [comment]
I think the window is become 2x the scale.
I tested setting by secondary monitor to 2x scale when the window is entirely on the primary monitor with 1x scale it correct, when any part of it is on the 2x monitor, it seemed to become 4x scale.

Possibly how scaling has worked has changed in Gtk4/the new clutter.

It seems like if any scaling up is enabled, this plugin, or libanimation is scaling the window up again by the next integer size - (125%, 150%, 175% all go to an extra 2x on top of the scale it is already).

I've included a pic of Settings being too large.
![IMG_20220124_112236](https://user-images.githubusercontent.com/179677/150774471-85d002f7-2d4a-418b-a78b-d9f6ab76780c.jpg)

**Comment by stuaxo** [comment]
Looking at the code of the JS version - 
https://github.com/hermes83/compiz-windows-effect/blob/master/libAnimationWrapper.js

The parts that use native coordinates probably need to be updated to take DPI into account.

Since DPI can be per monitor, if the window is over multiple monitors, the parts on different monitors may need to be drawn separately scaled with each monitors DPI.

**Comment by marcinx64** [comment]
With latest commit the problem with fractional scaling seems to be resolved.
@hermes83 are You planning also to refactor Compiz MagicLamp extension, which also have scaling factor issues?
Best Regards

**Comment by hermes83** [comment]
Hi @marcinx64,
thanks for the confirmation.
Yes I will. i have to fix a problem with this extension related to excessive use of cpu to paint the surface so i will focus on the magic lamp problems

**Comment by hermes83** [comment]
> With latest commit the problem with fractional scaling seems to be resolved. @hermes83 are You planning also to refactor Compiz MagicLamp extension, which also have issues with fractional scaling? Best Regards

Hi, with the latest release, "Compiz MagicLamp extension" should be fine too

**Comment by marcinx64** [comment]
Hi @hermes83 I'm already testing it, seems fine at the moment with fractional scaling working perfectly.
