### ISSUE TITLE
issue with scaling

### ISSUE THREAD

**Issue by ItzSveno** [hermes83/compiz-windows-effect#9]
if the scaling is something else than 100% moving the window makes it really big.

i also have fractional scaling if that matters.

**Comment by marcinx64** [comment]
Can confirm, happens on my system with experimental scaling turned on, on 100% no problem

https://user-images.githubusercontent.com/43246702/163583805-9e068298-ba1a-4658-b204-90214eabe228.mp4

.

**Comment by marcinx64** [comment]
Can confirm, happens on my system with experimental scaling turned on, on 100% no problem

https://user-images.githubusercontent.com/43246702/163584385-e95223a3-ae02-426c-b3f5-b7822b696186.mp4

**Comment by hermes83** [comment]
duplicate #5
